print("Let's play Silly Sentences!")
print(" ")
name = input("Enter a name: ")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
adverb = input("Enter a adverb: " )
food1 = input("Enter a food: ")
food2 = input("Enter another food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ")
print(" ")
print(name + " was planning a dream vacation to " + place + ".")
print(name + " was especially looking forward to trying the local")
print("cuisine, including " + adj1 + " " + food1 + " and " + food2 + ".")
print(" ")
print(name + " will have to practice the language " + adverb + " to")
print("make it easier to " + verb + " with people.")
print(" ")
print(name + " has a long list of sights to see, including the")
print(noun + " museum and the " + adj2 + " park.")